# EDA and Metric selection
- Look at, summarize, and clean the data.
- Scope out classification viability
- Determine the most relevant classification metric(s).

Import csv, load into a DataFrame, get info on the dataframe, and clean up DataFrame

In [1]:
# imports

import pandas as pd
import numpy as np

In [2]:
diabetes_df = pd.read_csv("diabetic_data_copy.csv")

In [3]:
diabetes_df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [4]:
diabetes_df.columns = diabetes_df.columns.str.strip()

In [5]:
diabetes_df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [6]:
diabetes_df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [7]:
diabetes_df_copy = diabetes_df.copy()

In [8]:
diabetes_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
encounter_id                101766 non-null int64
patient_nbr                 101766 non-null int64
race                        101766 non-null object
gender                      101766 non-null object
age                         101766 non-null object
weight                      101766 non-null object
admission_type_id           101766 non-null int64
discharge_disposition_id    101766 non-null int64
admission_source_id         101766 non-null int64
time_in_hospital            101766 non-null int64
payer_code                  101766 non-null object
medical_specialty           101766 non-null object
num_lab_procedures          101766 non-null int64
num_procedures              101766 non-null int64
num_medications             101766 non-null int64
number_outpatient           101766 non-null int64
number_emergency            101766 non-null int64
number_inpatient            101766 non-null int64
diag_1                      101766 non-null object
diag_2                      101766 non-null object
diag_3                      101766 non-null object
number_diagnoses            101766 non-null int64
max_glu_serum               101766 non-null object
A1Cresult                   101766 non-null object
metformin                   101766 non-null object
repaglinide                 101766 non-null object
nateglinide                 101766 non-null object
chlorpropamide              101766 non-null object
glimepiride                 101766 non-null object
acetohexamide               101766 non-null object
glipizide                   101766 non-null object
glyburide                   101766 non-null object
tolbutamide                 101766 non-null object
pioglitazone                101766 non-null object
rosiglitazone               101766 non-null object
acarbose                    101766 non-null object
miglitol                    101766 non-null object
troglitazone                101766 non-null object
tolazamide                  101766 non-null object
examide                     101766 non-null object
citoglipton                 101766 non-null object
insulin                     101766 non-null object
glyburide-metformin         101766 non-null object
glipizide-metformin         101766 non-null object
glimepiride-pioglitazone    101766 non-null object
metformin-rosiglitazone     101766 non-null object
metformin-pioglitazone      101766 non-null object
change                      101766 non-null object
diabetesMed                 101766 non-null object
readmitted                  101766 non-null object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [9]:
diabetes_df_copy = diabetes_df.rename(columns={'citoglipton':'sitagliptin'})

In [10]:
diabetes_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
encounter_id                101766 non-null int64
patient_nbr                 101766 non-null int64
race                        101766 non-null object
gender                      101766 non-null object
age                         101766 non-null object
weight                      101766 non-null object
admission_type_id           101766 non-null int64
discharge_disposition_id    101766 non-null int64
admission_source_id         101766 non-null int64
time_in_hospital            101766 non-null int64
payer_code                  101766 non-null object
medical_specialty           101766 non-null object
num_lab_procedures          101766 non-null int64
num_procedures              101766 non-null int64
num_medications             101766 non-null int64
number_outpatient           101766 non-null int64
number_emergency            101766 non-null int64
number_inpatient            101766 non-null int64
diag_1                      101766 non-null object
diag_2                      101766 non-null object
diag_3                      101766 non-null object
number_diagnoses            101766 non-null int64
max_glu_serum               101766 non-null object
A1Cresult                   101766 non-null object
metformin                   101766 non-null object
repaglinide                 101766 non-null object
nateglinide                 101766 non-null object
chlorpropamide              101766 non-null object
glimepiride                 101766 non-null object
acetohexamide               101766 non-null object
glipizide                   101766 non-null object
glyburide                   101766 non-null object
tolbutamide                 101766 non-null object
pioglitazone                101766 non-null object
rosiglitazone               101766 non-null object
acarbose                    101766 non-null object
miglitol                    101766 non-null object
troglitazone                101766 non-null object
tolazamide                  101766 non-null object
examide                     101766 non-null object
sitagliptin                 101766 non-null object
insulin                     101766 non-null object
glyburide-metformin         101766 non-null object
glipizide-metformin         101766 non-null object
glimepiride-pioglitazone    101766 non-null object
metformin-rosiglitazone     101766 non-null object
metformin-pioglitazone      101766 non-null object
change                      101766 non-null object
diabetesMed                 101766 non-null object
readmitted                  101766 non-null object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [11]:
diabetes_df_copy=diabetes_df_copy.drop(['encounter_id', 'patient_nbr', 'weight', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'payer_code', 'medical_specialty',  'num_lab_procedures', 'num_procedures', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult', 'readmitted'], axis = 1)

In [12]:
# count of number of A1C result
# A1C_count = diabetes_df_copy.groupby('A1Cresult')['A1Cresult'].count()
# A1C_count.head()

In [13]:
# create dummy variables for medication.
# list of medications: ['metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'sitagliptin', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone']

diabetes_df_copy['metformin'] = diabetes_df_copy['metformin'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['repaglinide'] = diabetes_df_copy['repaglinide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['nateglinide'] = diabetes_df_copy['nateglinide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['chlorpropamide'] = diabetes_df_copy['chlorpropamide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['glimepiride'] = diabetes_df_copy['glimepiride'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['acetohexamide'] = diabetes_df_copy['acetohexamide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['glipizide'] = diabetes_df_copy['glipizide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['glyburide'] = diabetes_df_copy['glyburide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['tolbutamide'] = diabetes_df_copy['tolbutamide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['pioglitazone'] = diabetes_df_copy['pioglitazone'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['rosiglitazone'] = diabetes_df_copy['rosiglitazone'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['acarbose'] = diabetes_df_copy['acarbose'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['miglitol'] = diabetes_df_copy['miglitol'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['troglitazone'] = diabetes_df_copy['troglitazone'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['tolazamide'] = diabetes_df_copy['tolazamide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['examide'] = diabetes_df_copy['examide'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['sitagliptin'] = diabetes_df_copy['sitagliptin'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['insulin'] = diabetes_df_copy['insulin'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['glyburide-metformin'] = diabetes_df_copy['glyburide-metformin'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['glipizide-metformin'] = diabetes_df_copy['glipizide-metformin'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['glimepiride-pioglitazone'] = diabetes_df_copy['glimepiride-pioglitazone'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['metformin-rosiglitazone'] = diabetes_df_copy['metformin-rosiglitazone'].map({"Up":1, "Down":2, "Steady":3, "No":4})
diabetes_df_copy['metformin-pioglitazone'] = diabetes_df_copy['metformin-pioglitazone'].map({"Up":1, "Down":2, "Steady":3, "No":4})

In [14]:
# create dummy variables.

diabetes_df_copy['age'] = diabetes_df_copy['age'].map({'[0-10)':1, '[10-20)':2, '[20-30)':3, '[30-40)':4, '[40-50)':5, '[50-60)':6, '[60-70)':7,'[70-80)':8, '[80-90)':9, '[90-100)':10})
diabetes_df_copy['gender'] = diabetes_df_copy['gender'].map({'Male':1, 'Female':0})
diabetes_df_copy['race'] = diabetes_df_copy['race'].map({'?':0 ,'Asian':1, 'Caucasian':2, 'AfricanAmerican':3, 'Other':4})
diabetes_df_copy['diabetesMed'] = diabetes_df_copy['diabetesMed'].map({'Yes':1, 'No':0})
diabetes_df_copy['change'] = diabetes_df_copy['change'].map({'Ch':1, 'No':0})

In [15]:
# replace all NaN in race, gender, and change
# .replace
# .fillna(0)
# with numpy: .replace(np.nan, 0)
diabetes_df_copy = diabetes_df_copy.fillna (0)

In [ ]:
# group by Change of  Medication. 
# indicates if there was any diabetic medication prescribed.
# Values: "yes" and "no"
# Change_in_Medication_df = diabetes_df_copy.groupby('change')['', '']

In [16]:
diabetes_df_copy.head()

,race,gender,age,num_medications,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,...,examide,sitagliptin,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed
0,2.0,0.0,1,1,1,4,4,4,4,4,...,4,4,4,4,4,4,4,4,0,0
1,2.0,0.0,2,18,9,4,4,4,4,4,...,4,4,1,4,4,4,4,4,1,1
2,3.0,0.0,3,13,6,4,4,4,4,4,...,4,4,4,4,4,4,4,4,0,1
3,2.0,1.0,4,16,7,4,4,4,4,4,...,4,4,1,4,4,4,4,4,1,1
4,2.0,1.0,5,8,5,4,4,4,4,4,...,4,4,3,4,4,4,4,4,1,1

In [20]:
diabetes_df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 30 columns):
race                        101766 non-null float64
gender                      101766 non-null float64
age                         101766 non-null int64
num_medications             101766 non-null int64
number_diagnoses            101766 non-null int64
metformin                   101766 non-null int64
repaglinide                 101766 non-null int64
nateglinide                 101766 non-null int64
chlorpropamide              101766 non-null int64
glimepiride                 101766 non-null int64
acetohexamide               101766 non-null int64
glipizide                   101766 non-null int64
glyburide                   101766 non-null int64
tolbutamide                 101766 non-null int64
pioglitazone                101766 non-null int64
rosiglitazone               101766 non-null int64
acarbose                    101766 non-null int64
miglitol                    101766 non-null int64
troglitazone                101766 non-null int64
tolazamide                  101766 non-null int64
examide                     101766 non-null int64
sitagliptin                 101766 non-null int64
insulin                     101766 non-null int64
glyburide-metformin         101766 non-null int64
glipizide-metformin         101766 non-null int64
glimepiride-pioglitazone    101766 non-null int64
metformin-rosiglitazone     101766 non-null int64
metformin-pioglitazone      101766 non-null int64
change                      101766 non-null float64
diabetesMed                 101766 non-null int64
dtypes: float64(3), int64(27)
memory usage: 23.3 MB

In [17]:
# save a new df

# A1C_Result_Groupby_df.to_csv("A1C_Result_Groupby_df.csv")

# (done) 
diabetes_df_copy.to_csv("Diabetes_Update_Df.csv", index = False)

In [18]:
diabetes_update_df = pd.read_csv("Diabetes_Update_Df.csv")

In [19]:
diabetes_update_df.head()

,race,gender,age,num_medications,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,...,examide,sitagliptin,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed
0,2.0,0.0,1,1,1,4,4,4,4,4,...,4,4,4,4,4,4,4,4,0,0
1,2.0,0.0,2,18,9,4,4,4,4,4,...,4,4,1,4,4,4,4,4,1,1
2,3.0,0.0,3,13,6,4,4,4,4,4,...,4,4,4,4,4,4,4,4,0,1
3,2.0,1.0,4,16,7,4,4,4,4,4,...,4,4,1,4,4,4,4,4,1,1
4,2.0,1.0,5,8,5,4,4,4,4,4,...,4,4,3,4,4,4,4,4,1,1

In [20]:
diabetes_update_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 30 columns):
race                        101766 non-null float64
gender                      101766 non-null float64
age                         101766 non-null int64
num_medications             101766 non-null int64
number_diagnoses            101766 non-null int64
metformin                   101766 non-null int64
repaglinide                 101766 non-null int64
nateglinide                 101766 non-null int64
chlorpropamide              101766 non-null int64
glimepiride                 101766 non-null int64
acetohexamide               101766 non-null int64
glipizide                   101766 non-null int64
glyburide                   101766 non-null int64
tolbutamide                 101766 non-null int64
pioglitazone                101766 non-null int64
rosiglitazone               101766 non-null int64
acarbose                    101766 non-null int64
miglitol                    101766 non-null int64
troglitazone                101766 non-null int64
tolazamide                  101766 non-null int64
examide                     101766 non-null int64
sitagliptin                 101766 non-null int64
insulin                     101766 non-null int64
glyburide-metformin         101766 non-null int64
glipizide-metformin         101766 non-null int64
glimepiride-pioglitazone    101766 non-null int64
metformin-rosiglitazone     101766 non-null int64
metformin-pioglitazone      101766 non-null int64
change                      101766 non-null int64
diabetesMed                 101766 non-null int64
dtypes: float64(2), int64(28)
memory usage: 23.3 MB